name = "UnicodeNext"
uuid = "7b9d9d2f-29eb-4111-b31d-f1cfc33d1412"
authors = ["Claire Foster <aka.c42f@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
